name: Infra Test

on: 
    push:
      branches:
        - main
      paths-ignore:
        - 'CHANGELOG.md'
        - 'gcp-node/package.json'
        - 'gcp-node/package-lock.json'
        - 'package.json'
        - 'package-lock.json'

jobs: 
    versioning-control:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.ACTIONS_TOKEN }}

            - name: Install and Build
              run: |
                cd gcp-node/ && npm install
